@VehicleParts.API_HostAddress = http://localhost:5046

GET {{VehicleParts.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{VehicleParts.API_HostAddress}}/api/Sales/create-sale
Content-Type: application/json

{
  "customerId": 1,
  "items": [
    {
      "price": 3000,
      "quantity": 2
    }
  ]
}

###

POST {{VehicleParts.API_HostAddress}}/api/Sales/calculate-loyalty-discount
Content-Type: application/json

{
  "customerId": 1,
  "items": [
    {
      "price": 3000,
      "quantity": 2
    }
  ]
}